Repository Likelion-YeungNam-Univ/13th-StartPoint-web, pull requests merged in 2025-08, with the labels that each got.

#2 [feat/#1] 웹페이지 초기 구성
  src/App.jsx
  src/Layout.jsx
  src/NavBar.jsx
  src/assets/SPO_Logo.png
  src/assets/react.svg
  src/pages/Home.jsx
  src/pages/MarketResearch.jsx
  src/pages/Mentoring.jsx
  src/pages/NotFound.jsx
Labels: Feature

#7 [feat/#6] - 로그인 화면 UI 구현
  src/App.jsx
  src/NavBar.jsx
  src/pages/Login.jsx
  src/pages/MyPage.jsx
  src/pages/mypage.css
Labels: Feature

#8 [feat/#4] - 마이페이지 화면 UI 구현
  src/App.jsx
  src/NavBar.jsx
Labels: Feature

#34 [Style/#23] - 회원가입 페이지 UI 디자인 수정
  src/pages/SignUp.jsx
Labels: Style

#37 [feat/#35] Footer UI 구현
  package-lock.json
  package.json
  src/Footer.jsx
  src/Layout.jsx
  src/assets/Analysis.svg
  src/assets/Check.svg
  src/assets/Githublogo.svg
  src/assets/Icon.svg
  src/assets/Industry.svg
  src/assets/Population.svg
  src/assets/SPO_Logo_dark.png
  src/assets/Sales.svg
  src/assets/Vector.svg
  src/pages/MarketResult.jsx
Labels: Feature

#36 [Style/#14] - 챗봇 ui 수정
  S.png
  package-lock.json
  package.json
  src/assets/S.png
  src/pages/ChatBot.jsx
  src/pages/Home.jsx
Labels: Style

#47 [Style/#40]-Footer UI 수정
  package-lock.json
  package.json
  src/Footer.jsx
  src/assets/Notandum.svg
  src/assets/SPO_Logo_Footer.svg
  src/assets/SPO_Logo_dark.png
  src/assets/SadIcon.svg
  src/assets/Vector.svg
  src/pages/MarketResult.jsx
  src/pages/Mentoring.jsx
Labels: Style

#48 [style/#42] - 홈 및 네비게이션 바 UI 피드백 반영
  package-lock.json
  package.json
  src/Layout.jsx
  src/NavBar.jsx
  src/assets/Vector.svg
  src/fonts/Pretendard-Black.ttf
  src/fonts/Pretendard-Bold.ttf
  src/fonts/Pretendard-ExtraBold.ttf
  src/fonts/Pretendard-ExtraLight.ttf
  src/fonts/Pretendard-Light.ttf
  src/fonts/Pretendard-Medium.ttf
  src/fonts/Pretendard-Regular.ttf
  src/fonts/Pretendard-SemiBold.ttf
  src/fonts/Pretendard-Thin.ttf
  src/index.css
  src/pages/Home.jsx
  src/pages/MarketResult.jsx
  src/pages/Mentoring.jsx
Labels: Style

#71 [fix/69]-pracLoading
  src/pages/MarketResult.jsx
Labels: Style

#92 [Refac] 홈 화면 피드백 반영
  src/pages/Home.jsx
Labels: Refactor, Style

#93 [refac] 마이페이지 추가 수정
  src/pages/MyPage.jsx
  src/pages/SignUp.jsx
Labels: Refactor, Style

#94 [refac] Footer 아래 여백 제거
  src/Footer.jsx
Labels: Refactor, Style

#101 [refac] 2차 피드백
  src/Footer.jsx
  src/pages/Home.jsx
  src/pages/MyPage.jsx
  src/pages/SignUp.jsx
Labels: Refactor, Style

#103 [style] 챗봇 호버 기능 수정
  src/pages/ChatBot.jsx
Labels: Style
